//改变文章
export const CHANGE_ARTICLE_DETAIL  = "CHANGE_ARTICLE_DETAIL"

//改变评论的数组
export const CHANGE_ARTICLE_COMMENT_LIST = "CHANGE_ARTICLE_COMMENT_LIST"

//改变锚点数组
export const CHANGE_ANCHOR_LIST="CHANGE_ANCHOR_LIST"